### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by elcollins** [InnovativeReelTechnologies/home#114]
- [x] Change "PHONE" to say "CALL" like it does in the footer
- [x] Remove the word "address" after Email in both submission forms
- [x] Pro-Staffer to Pro Staffer
- [ ] Can "Pro Staff" in Nav go under support?
- [ ] On the CONTACT US and PRO STAFF SUBMISSION pages, can we align these to the left more? On the contact page, there's a huge gap. The submission box should be aligned left and then keep the extra info where it's at on the right.

**Comment by ndkline** [comment]
- [ ] ~Can "Pro Staff" in Nav go under support?~
- No. It isn't support. 
- [ ] ~On the CONTACT US and PRO STAFF SUBMISSION pages, can we align these to the left more? On the contact page, there's a huge gap. The submission box should be aligned left and then keep the extra info where it's at on the right.~
- No.
