### ISSUE TITLE
Patents

### ISSUE THREAD

**Issue by elcollins** [InnovativeReelTechnologies/home#122]
- [ ] Should we have an image of the product on every page so we're consistent?
- [ ] Make all titles of the page the exact title on the patent
- [ ] Make sure "Abstract" is on every page as a header
- [x] Image is too large in comparison to the others on the "Fishing Reel Handle" patent page - this page is also not consistent with the others. Spell out dates and format everything the same please
- [x] Add other listed patents (see Erin or April)
- [x] Remove "method for manufacturing link" because it links to the same page

**Comment by ndkline** [comment]
- [ ] Should we have an image of the product on every page so we're consistent?
- Not needed. 
- [ ] Make all titles of the page the exact title on the patent
- No. Hurts SEO and not necessary. The legal title is in the referenced document itself. The page should optimize clickthroughs to it. "Fishing Reel Leg" isn't as strong as "Spin Power Grip"
- [ ] Make sure "Abstract" is on every page as a header
- Not every is an abstract, only ones that have a "Abstract" title are. The others are just normal description that do not appear on the legal document itself.
