### ISSUE TITLE
Reel Description Updates

### ISSUE THREAD

**Issue by elcollins** [InnovativeReelTechnologies/home#128]
**300 Series**
- [x] Subhead: The IRT300 spinning reel is versatile, easily balancing out size and power.
- [x] Details: The IRT300 spinning reel is versatile, easily balancing out size and power. / This spinning reel is ideal for kayak and in-shore fishing applications. This reel works well in both saltwater (Flounder, Redfish, etc) and in fresh water (Small Mouth Bass, Salmon, Muskie, etc). / The IRT300 nicely complements a rod with a 8 to 12 pound test monofilament line or a 15-pound braided line.

**400 Series**
- [x] Subhead: The IRT400 spinning reel is designed for surf and inshore applications.
- [x] Details: The IRT400 spinning reel is designed for surf and inshore applications. / This spinning reel works well for catching Bull Redfish, Striped Bass, Flounder, Bluefish, Cobia, Small Mouth Bass, Salmon, Muskie, Pike, and other medium to large sized saltwater and fresh water fish. / The IRT400 is an all around great reel for surf, pier, and inshore fishing.  It is best outfitted with a 10 to 15 pound test monofilament line, a 20-pound braided line, and a medium to fast action rod.

**500 Series**
- [x] Subhead: The IRT500 is the largest of our inshore spinning reel series and is ideal for heavier freshwater applications.
- [x] Details: This reel will grab the attention of bigger fish (i.e. Stripers, Bluefish, etc.) when used with live or artificial bait. The IRT500 can also be combined with a medium to heavy action rod to cast from jetties.

**600 Series**
- [x] Subhead: The IRT600 spinning reel is a reliable, large reel with unfailing size and power.
- [x] Details: The IRT600 spinning reel is a reliable, large reel with unfailing size and power. / The reel’s size is comfortable for lighter saltwater duties, such as pier and bay fishing. It also provides the line capacity for heavier applications, such as fighting a striped bass from the surf with a heavy 12-foot rod. / When used for freshwater applications, this reel will handle Steelhead, Salmon, or Muskie and complement a medium to heavy strength rod.

**700 Series**
- [x] Subhead: The IRT700 spinning reel will help you win the fight against larger fish.
- [x] Details: The IRT700 spinning reel will help you win the fight against larger fish. / This is the reel that you want when battling White Marlin, Sailfish, king Mackerel, or Gaffer Dolphin. The IRT700 is also ideal for Blackfin Tuna and larger sharks.

**800 Series**
- [x] Subhead: The IRT800 spinning reel is designed for heavy surf fishing and medium offshore duties.
- [x] Details: The IRT800 spinning reel is designed for heavy surf fishing and medium offshore duties. / This reel is IRT's largest reel to date and is designed for all of your heavy-duty fishing needs. From Kingfish and Wahoo, to sharks and Gaffer sized Mahi Mahi, this reel is the best. / In addition, adding the dual drag to this reel will increase the drag capacity by 55 to 65 pounds.
---
Nick, these are temporary fixes most likely until I come up with something better, but I'd rather we have them cleaner for now.

**Comment by ndkline** [comment]
Sounds good!

I'm sure Ross wouldn't have a problem being an idea springboard for the future edits. In the meantime these will work. Taking the changes live shortly
